# Generated by Django 2.1.1 on 2018-09-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0001_Initial_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respondent',
            options={'verbose_name_plural': 'Respondent Data'},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('user', 'question')},
        ),
    ]
